name: frees
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  another_flutter_splash_screen: ^1.1.4
  cached_network_image: ^3.2.3
  change_app_package_name: ^1.1.0
  circular_countdown_timer: ^0.2.3
  cloud_firestore: ^4.5.1
  country_picker: ^2.0.19
  country_state_city_picker: ^1.2.8
  cryptography: ^2.5.0
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.2.1+3
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  firebase_database: ^10.2.2
  firebase_messaging: ^14.6.5
  firebase_phone_auth_handler: ^1.0.8
  firebase_storage: ^11.2.2
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_inapp_purchase: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.0.3+4
  flutter_spinkit: ^5.1.0
  flutter_splash_screen: ^2.0.1+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.5
  flutter_timer_countdown: ^1.0.5
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  in_app_purchase: ^3.1.7
  in_app_purchase_storekit: ^0.3.6+4
  intl: ^0.18.1
  intl_phone_field: ^3.1.0
  location: ^5.0.1
  native_ads_flutter: ^1.0.7
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  rate_my_app: ^2.0.0
  shared_preferences: ^2.0.15
  smooth_star_rating_nsafe: 1.0.0+1
  sqflite: ^2.2.6
  syncfusion_flutter_gauges: ^23.1.43
  timer_count_down: ^2.2.2
  timezone: ^0.9.2
  url_launcher: ^6.2.1
  uuid: ^4.1.0

dependency_overrides:
  firebase_core_platform_interface: ^4.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/racetimelogo.svg
    - assets/fire.png
    - assets/logogifting.png
    - assets/defaultprofilephoto.png
    - assets/frees.png
    - assets/giftbox.png
    - assets/logo2.png
    - assets/noun-giftbox-4804968.png
    - assets/frees.png
    - assets/iconfrees.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
