// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAR2MZN7PeIW3sHipxf8o_UMFU3jQ5Lc',
    appId: '1:990581988375:web:4f10110f7e44651d7dd052',
    messagingSenderId: '990581988375',
    projectId: 'freethings-257b6',
    authDomain: 'freethings-257b6.firebaseapp.com',
    databaseURL:
        'https://freethings-257b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freethings-257b6.appspot.com',
    measurementId: 'G-6195VT77GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFwuFnKMvqtqG5DJI_JN-7ub1ceJCB6I',
    appId: '1:990581988375:android:63d5f83115ccce4c7dd052',
    messagingSenderId: '990581988375',
    projectId: 'freethings-257b6',
    databaseURL:
        'https://freethings-257b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freethings-257b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzlzp3DUt-OExgVgP39-XMfBoZzoC-yc',
    appId: '1:990581988375:ios:e53b4e20d479cd677dd052',
    messagingSenderId: '990581988375',
    projectId: 'freethings-257b6',
    databaseURL: 'https://freethings-257b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freethings-257b6.appspot.com',
    androidClientId: '990581988375-3spvl0idnpfq9b5dd9p1opl89f0o6ii5.apps.googleusercontent.com',
    iosClientId: '990581988375-n5913t4nsfk1trsdhcb3vi3992tqsbqc.apps.googleusercontent.com',
    iosBundleId: 'com.freecycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzlzp3DUt-OExgVgP39-XMfBoZzoC-yc',
    appId: '1:990581988375:ios:27dd261e8a176e087dd052',
    messagingSenderId: '990581988375',
    projectId: 'freethings-257b6',
    databaseURL:
        'https://freethings-257b6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'freethings-257b6.appspot.com',
    iosClientId:
        '990581988375-947gsnkgc9so4shs08qtrnrave4n0j9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.Freecycle',
  );
}